### ISSUE TITLE
Tests with live Avalara integration fail

### ISSUE THREAD

**Issue by tesserakt** [bonobos/spree_avatax#53]
Just added my Avalara integration, got this: 

```
1) Tax Calculation without discounts computes taxes for a line item
     Failure/Error: expect {
       result should have changed, but is still #<BigDecimal:1017d72b8,'0.0',9(27)>
     # ./spec/features/tax_calculation_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) Tax Calculation with discounts computes taxes for a line item
     Failure/Error: expect do
       result should have changed, but is still #<BigDecimal:10d69e138,'0.0',9(27)>
     # ./spec/features/tax_calculation_spec.rb:56:in `block (3 levels) in <top (required)>'
```

Also it looks like your travis integration is failing too.

This is on 2-2-stable. I'll see what I can find.

**Comment by tesserakt** [comment]
This is on 2-2-stable

**Comment by tesserakt** [comment]
I'll investigate to see what I find.

**Comment by tesserakt** [comment]
For some reason all my responses  are coming back as exempt and are also not being logged by the sandbox account.

**Comment by tesserakt** [comment]
Nevermind, had to turn on NY as a jurisdiction for my company in Avalara.
